version: "3.9"

networks:
 deploy-mentor:
  driver: bridge
 
services:
 booking_api:
  build:
   context: .
   dockerfile: ./Booking.API/Dockerfile
  container_name: booking_api
  ports:
   - '7005:7005'
  depends_on:
   - booking_db 
  entrypoint: /bin/sh -c "dotnet Booking.API.dll"
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ASPNETCORE_URLS=https://+:7005
  networks:
   - deploy-mentor
 
 booking_db:
  container_name: booking_db
  environment:
   - ACCEPT_EULA=Y
   - MSSQL_SA_PASSWORD=Book1!pass 
  image: mcr.microsoft.com/mssql/server:2022-latest
  ports:
   - '5000:1433'
  networks:
   - deploy-mentor

 mentor_api:
  build:
   context: .
   dockerfile: ./Mentors.API/Dockerfile 
  container_name: mentor_api
  ports:
   - '7001:7001'
   - '7002:7002'
  depends_on:
   - mentor_db 
  entrypoint: /bin/sh -c "dotnet Mentors.API.dll"
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ASPNETCORE_URLS=https://+:7001
   - GRPC_DNS_RESOLVER=native
  networks:
   - deploy-mentor

 mentor_db:
  container_name: mentor_db
  environment:
   - DatabaseUser=sa
   - ACCEPT_EULA=Y
   - MSSQL_SA_PASSWORD=Ms!1password 
  image: mcr.microsoft.com/mssql/server:2022-latest
  ports:
   - '5015:1433'
  networks:
   - deploy-mentor

 identity_db:
  container_name: identity_db
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  image: postgres:latest
  ports:
   - '5432:5432'
  volumes:
   - db:/var/lib/postgresql/data
  networks:
   - deploy-mentor

 pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_4
    networks:
      - deploy-mentor
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=7777
    depends_on:
      - identityserver
 
 identityserver:
  container_name: identity_server
  build:
   context: .
   dockerfile: Identity.API/Dockerfile 
  depends_on:
   - identity_db
  entrypoint: /bin/sh -c "update-ca-certificates && dotnet Identity.API.dll"
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ASPNETCORE_URLS=https://+:443
   - CONNECTIONSTRINGS__IDENTITYCONNECTION=Server=identity_db;Port=5432;Database=Identity;User Id=postgres;Password=password;
   - CONNECTIONSTRINGS__IDENTITYSERVERCONNECTION=Server=identity_db;Port=5432;Database=IdentityServer;User Id=postgres;Password=password;  
  ports:
   - '443:443'
  networks:
   - deploy-mentor

volumes:
  db:    