apiVersion: apps/v1
kind: Deployment
metadata:
 name: booking_api
 labels: 
  name: booking_api
  app: mentorplatform

spec:  
 containers:
  - name: booking_api   
    image: alexandrarudaya/booking_api:latest
    ports:
    - containerPort: 7005