apiVersion: apps/v1
kind: Deployment
metadata:
 name: chat_db
 labels: 
  name: chat_db
  app: mentorplatform

spec:  
 containers:
  - name: chat_db  
    image: mcr.microsoft.com/mssql/server:2022-latest
    env:
     - name: ACCEPT_EULA
       value: "Y"
     - name: MSSQL_SA_PASSWORD
       value: Chat!pass
    ports:
    - containerPort: 5001