apiVersion: v1
kind: Service
metadata:
 name: gateway-service
 labels: 
  name: gateway-service
  app: mentorplatform

spec: 
 type: LoadBalancer
 ports:
  - protocol: TCP
    port: 7008
    targetPort: 7008
 selector:
  name: gateway
  app: mentorplatform 