apiVersion: apps/v1
kind: Deployment
metadata:
 name: gateway
 labels: 
  name: gateway
  app: mentorplatform

spec:  
 containers:
  - name: gateway   
    image: alexandrarudaya/gateway:latest
    ports:
    - containerPort: 7008