apiVersion: apps/v1
kind: Deployment
metadata:
 name: gateway
 labels: 
  name: gateway
  app: mentorplatform

spec:
 replicas: 1  
 selector:
  matchLabels:
   name: gateway
   app: mentorplatform
 template:
  metadata:
   labels:
    name: gateway
    app: mentorplatform
  spec:
   containers:
    - name: gateway  
      image: alexandrarudaya/gateway:latest
      ports:
       - containerPort: 7008