apiVersion: apps/v1
kind: Deployment
metadata:
 name: identity-api
 labels: 
  name: identity-api
  app: mentorplatform

spec:
 replicas: 1  
 selector:
  matchLabels:
   name: identity-api
   app: mentorplatform
 template:
  metadata:
   labels:
    name: identity-api
    app: mentorplatform
  spec:
   containers:
    - name: identity-server   
      image: alexandrarudaya/identity_api:latest
      ports:
       - containerPort: 443
      env:
       - name: ElasticConfiguration__Uri
         value: "http://elasticsearch:9200"