apiVersion: v1
kind: Service
metadata:
 name: identity-db
 labels: 
  name: identitydb-service
  app: mentorplatform

spec:  
 ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
 selector:
  name: identity-db
  app: mentorplatform