apiVersion: apps/v1
kind: Deployment
metadata:
 name: identity-db
 labels: 
  name: identity-db
  app: mentorplatform

spec:
 replicas: 1  
 selector:
  matchLabels:
   name: identity-db
   app: mentorplatform
 template:
  metadata:
   labels:
    name: identity-db
    app: mentorplatform
  spec:
   containers:
    - name: identity-db  
      image: postgres:latest
      env:
       - name: POSTGRES_USER
         value: postgres
       - name: POSTGRES_PASSWORD
         value: password
      ports:
       - containerPort: 5432