apiVersion: v1
kind: Service
metadata:
 name: identity-service
 labels: 
  name: identity-service
  app: mentorplatform

spec:  
 type: LoadBalancer
 ports:
  - protocol: TCP
    port: 443
    targetPort: 443
 selector:
  name: identity-api
  app: mentorplatform