apiVersion: v1
kind: Service
metadata:
 name: kibana
 labels: 
  name: kibana-service
  app: mentorplatform

spec:  
 ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
 selector:
  name: kibana
  app: mentorplatform   