apiVersion: v1
kind: Service
metadata:
 name: mentor-db
 labels: 
  name: mentordb-service
  app: mentorplatform

spec:  
 ports:
  - protocol: TCP
    port: 5015
    targetPort: 1433
 selector:
  name: mentor-db
  app: mentorplatform