apiVersion: v1
kind: Service
metadata:
 name: mongodb
 labels: 
  name: mongodb-service
  app: mentorplatform

spec:  
 ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
 selector:
  name: mongodb
  app: mentorplatform