apiVersion: v1
kind: Deployment
metadata:
 name: mongodb
 labels: 
  name: mongodb
  app: mentorplatform

spec:  
 containers:
  - name: mongodb  
    image: mongo:latest
    env:
     - name: MONGO_INITDB_ROOT_USERNAME
       value: root
     - name: MONGO_INITDB_ROOT_PASSWORD
       value: mongo123
    ports:
    - containerPort: 27017