apiVersion: v1
kind: Service
metadata:
 name: rabbitmq
 labels: 
  name: rabbitmq-service
  app: mentorplatform

spec:  
 ports:
  - protocol: TCP
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    protocol: TCP
    port: 15672
    targetPort: 15672
 selector:
  name: rabbitmq
  app: mentorplatform