apiVersion: apps/v1
kind: Deployment
metadata:
 name: rabbitmq
 labels: 
  name: rabbitmq
  app: mentorplatform

spec:
 replicas: 1  
 selector:
  matchLabels:
   name: rabbitmq
   app: mentorplatform
 template:
  metadata:
   labels:
    name: rabbitmq
    app: mentorplatform
  spec:
   containers:
    - name: mentor-queue  
      image: rabbitmq:latest
      ports:
       - containerPort: 5672
       - containerPort: 15672