apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis
 labels: 
  name: redis
  app: mentorplatform

spec:
 replicas: 1  
 selector:
  matchLabels:
   name: redis
   app: mentorplatform
 template:
  metadata:
   labels:
    name: redis
    app: mentorplatform
  spec:
   containers:
    - name: redis  
      image: redis:latest
      ports:
       - containerPort: 6379