apiVersion: v1
kind: Service
metadata:
 name: redis
 labels: 
  name: redis-service
  app: mentorplatform

spec:  
 ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
 selector:
  name: redis
  app: mentorplatform   